// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1WFFpIhBy4-vtU-S6enG9IxcVvnhdgk8',
    appId: '1:223456824914:web:f16bda331ec41c56b1d98b',
    messagingSenderId: '223456824914',
    projectId: 'chatapp-lv16',
    authDomain: 'chatapp-lv16.firebaseapp.com',
    storageBucket: 'chatapp-lv16.firebasestorage.app',
    measurementId: 'G-PPLPCQ841C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWaZnhtS8_L1Gb_pVPUyA5gmsIdb-_iNA',
    appId: '1:223456824914:android:ee8e3f83e610eab0b1d98b',
    messagingSenderId: '223456824914',
    projectId: 'chatapp-lv16',
    storageBucket: 'chatapp-lv16.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuOrvya6jKTSCzl8oOACD9FeRE4e3Zo9g',
    appId: '1:223456824914:ios:8f6f16ab682684ffb1d98b',
    messagingSenderId: '223456824914',
    projectId: 'chatapp-lv16',
    storageBucket: 'chatapp-lv16.firebasestorage.app',
    iosBundleId: 'com.example.messengerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuOrvya6jKTSCzl8oOACD9FeRE4e3Zo9g',
    appId: '1:223456824914:ios:8f6f16ab682684ffb1d98b',
    messagingSenderId: '223456824914',
    projectId: 'chatapp-lv16',
    storageBucket: 'chatapp-lv16.firebasestorage.app',
    iosBundleId: 'com.example.messengerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1WFFpIhBy4-vtU-S6enG9IxcVvnhdgk8',
    appId: '1:223456824914:web:c56a7fb733c415f1b1d98b',
    messagingSenderId: '223456824914',
    projectId: 'chatapp-lv16',
    authDomain: 'chatapp-lv16.firebaseapp.com',
    storageBucket: 'chatapp-lv16.firebasestorage.app',
    measurementId: 'G-FH73YQRBMM',
  );
}
